# Generated by Django 5.2.5 on 2025-08-17 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('password_hash', models.CharField(max_length=255, verbose_name='비밀번호 해시')),
                ('name', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('position', models.CharField(max_length=50, verbose_name='직급')),
                ('phone_number', models.CharField(max_length=20, verbose_name='핸드폰 번호')),
                ('role_level', models.IntegerField(choices=[(0, '게스트'), (1, '실무자'), (2, '관리자')], default=0, verbose_name='권한 레벨')),
                ('status', models.CharField(choices=[('active', '활성'), ('locked', '잠금'), ('suspended', '정지'), ('deleted', '삭제')], default='locked', max_length=20, verbose_name='계정 상태')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='로그인 실패 횟수')),
                ('last_failed_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 실패 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='최종 로그인 시간')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
            },
        ),
    ]
