# Generated by Django 5.2.5 on 2025-10-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', '활성'), ('locked', '잠금'), ('deleted', '삭제')], default='locked', max_length=20, verbose_name='계정 상태'),
        ),
    ]
