# Generated by Django 5.2.5 on 2025-10-01 10:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('nonconformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ccr_uid', models.CharField(editable=False, max_length=26, unique=True, verbose_name='CCR UID')),
                ('occurrence_date', models.DateField(verbose_name='발생일')),
                ('ccr_no', models.CharField(max_length=50, verbose_name='CCR NO')),
                ('vendor', models.CharField(max_length=100, verbose_name='업체명')),
                ('product_name', models.CharField(max_length=100, verbose_name='품명')),
                ('defect_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='부적합 수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='단가')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='합계')),
                ('complaint_content', models.TextField(verbose_name='고객 불만 내용')),
                ('action_content', models.TextField(blank=True, null=True, verbose_name='조치 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('cause_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonconformance.defectcause', verbose_name='발생원인 코드')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaints', to='accounts.user', verbose_name='작성자')),
                ('defect_type_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonconformance.defecttype', verbose_name='불량유형 코드')),
            ],
            options={
                'verbose_name': '고객 불만',
                'verbose_name_plural': '고객 불만 목록',
                'db_table': 'customer_complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['occurrence_date'], name='idx_ccr_date'), models.Index(fields=['vendor'], name='idx_ccr_vendor'), models.Index(fields=['ccr_no'], name='idx_ccr_no'), models.Index(fields=['defect_type_code'], name='idx_ccr_defect_type'), models.Index(fields=['cause_code'], name='idx_ccr_cause_code')],
            },
        ),
    ]
