# Generated by Django 5.2.5 on 2025-10-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customercomplaint",
            name="action_completed",
            field=models.BooleanField(default=False, verbose_name="조치 완료 여부"),
        ),
    ]
