# Generated by Django 5.2.5 on 2025-09-07 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('schedule_uid', models.CharField(editable=False, max_length=26, unique=True)),
                ('type', models.CharField(choices=[('quality', '품질 일정'), ('personal', '개인 일정')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('description', models.TextField(blank=True, null=True)),
                ('importance', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_schedules', to='accounts.user')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정들',
                'db_table': 'schedules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='idx_schedules_date'), models.Index(fields=['type', 'importance'], name='idx_schedules_type_importance'), models.Index(fields=['owner'], name='idx_schedules_owner')],
            },
        ),
    ]
