# Generated by Django 5.2.5 on 2025-10-01 11:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kpi_uid', models.CharField(editable=False, max_length=26, unique=True, verbose_name='KPI UID')),
                ('year', models.IntegerField(verbose_name='연도')),
                ('kpi_type', models.CharField(choices=[('defect_rate', '불량율'), ('f_cost', 'F-COST'), ('complaints', '고객 불만 건수')], max_length=20, verbose_name='KPI 종류')),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='목표값')),
                ('unit', models.CharField(choices=[('%', '%'), ('ppm', 'ppm'), ('KRW', '원'), ('count', '건')], max_length=10, verbose_name='단위')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpi_targets', to='accounts.user', verbose_name='작성자')),
            ],
            options={
                'verbose_name': 'KPI 목표',
                'verbose_name_plural': 'KPI 목표 목록',
                'db_table': 'kpi_targets',
                'ordering': ['-year', 'kpi_type'],
                'indexes': [models.Index(fields=['year', 'kpi_type'], name='idx_year_kpi_type'), models.Index(fields=['kpi_type'], name='idx_kpi_type')],
                'constraints': [models.UniqueConstraint(fields=('year', 'kpi_type'), name='unique_year_kpi_type')],
            },
        ),
    ]
