# Generated by Django 5.2.5 on 2025-08-24 05:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_uid', models.CharField(editable=False, max_length=26, unique=True)),
                ('type', models.CharField(choices=[('inhouse', '사내 실적'), ('incoming', '수입검사 실적')], max_length=10)),
                ('date', models.DateField()),
                ('vendor', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('control_no', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('producer', models.CharField(max_length=100)),
                ('weekday_code', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], editable=False, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '실적 기록',
                'verbose_name_plural': '실적 기록들',
                'db_table': 'performance_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
