# Generated by Django 5.2.5 on 2025-08-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_records', to='accounts.user'),
        ),
    ]
