# Generated by Django 5.2.5 on 2025-10-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_producer_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='type',
            field=models.CharField(choices=[('inhouse', '사내'), ('incoming', '수입')], max_length=10),
        ),
    ]
