# Generated by Django 5.2.5 on 2025-09-07 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCause',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='코드')),
                ('category', models.CharField(choices=[('Material', 'Material(소재)'), ('Machine', 'Machine(설비)'), ('Man', 'Man(사람)'), ('Method', 'Method(방법)'), ('Measurement', 'Measurement(측정)'), ('Environment', 'Environment(환경)'), ('Other', '기타')], max_length=30, verbose_name='6M 분류')),
                ('name', models.CharField(max_length=100, verbose_name='내용')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '발생 원인',
                'verbose_name_plural': '발생 원인 목록',
                'db_table': 'defect_causes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DefectType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='내용')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '불량 유형',
                'verbose_name_plural': '불량 유형 목록',
                'db_table': 'defect_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Nonconformance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ncr_uid', models.CharField(editable=False, max_length=26, unique=True, verbose_name='NCR UID')),
                ('type', models.CharField(choices=[('inhouse', '사내'), ('incoming', '수입')], max_length=10, verbose_name='부적합 유형')),
                ('occurrence_date', models.DateField(verbose_name='발생일')),
                ('ncr_no', models.CharField(max_length=50, verbose_name='NCR NO')),
                ('vendor', models.CharField(max_length=100, verbose_name='업체명')),
                ('product_name', models.CharField(max_length=100, verbose_name='품명')),
                ('control_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='관리번호')),
                ('defect_qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='부적합 수량')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='단가')),
                ('weight_factor', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='가중치')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=18, verbose_name='합계')),
                ('detection_stage', models.CharField(blank=True, max_length=30, null=True, verbose_name='발견공정')),
                ('why1', models.CharField(blank=True, max_length=255, null=True, verbose_name='1Why')),
                ('why2', models.CharField(blank=True, max_length=255, null=True, verbose_name='2Why')),
                ('why3', models.CharField(blank=True, max_length=255, null=True, verbose_name='3Why')),
                ('why4', models.CharField(blank=True, max_length=255, null=True, verbose_name='4Why')),
                ('why5', models.CharField(blank=True, max_length=255, null=True, verbose_name='5Why')),
                ('root_cause', models.CharField(blank=True, max_length=255, null=True, verbose_name='최종불량원인')),
                ('operators', models.JSONField(blank=True, null=True, verbose_name='작업자')),
                ('process_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='공정/부서')),
                ('weekday_code', models.CharField(choices=[('MON', '월요일'), ('TUE', '화요일'), ('WED', '수요일'), ('THU', '목요일'), ('FRI', '금요일'), ('SAT', '토요일'), ('SUN', '일요일')], editable=False, max_length=3, verbose_name='요일')),
                ('note', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('cause_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonconformance.defectcause', verbose_name='발생원인 코드')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nonconformances', to='accounts.user', verbose_name='작성자')),
                ('defect_type_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nonconformance.defecttype', verbose_name='불량유형 코드')),
            ],
            options={
                'verbose_name': '부적합',
                'verbose_name_plural': '부적합 목록',
                'db_table': 'nonconformances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['occurrence_date'], name='idx_nc_date'), models.Index(fields=['type', 'occurrence_date'], name='idx_nc_type_date'), models.Index(fields=['vendor'], name='idx_nc_vendor'), models.Index(fields=['control_no'], name='idx_nc_control_no'), models.Index(fields=['defect_type_code'], name='idx_nc_defect_type'), models.Index(fields=['cause_code'], name='idx_nc_cause_code')],
            },
        ),
    ]
