# Generated by Django 5.2.5 on 2025-10-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="백업 일시"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="파일 크기")),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("auto", "자동"), ("manual", "수동")],
                        max_length=10,
                        verbose_name="백업 유형",
                    ),
                ),
                ("file_path", models.CharField(max_length=500, verbose_name="파일 경로")),
                ("note", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_records",
                        to="accounts.user",
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "백업 이력",
                "verbose_name_plural": "백업 이력 목록",
                "db_table": "backup_records",
                "ordering": ["-backup_date"],
            },
        ),
    ]
