# Generated by Django 5.2.5 on 2025-08-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', '로그인 성공'), ('LOGIN_FAILED', '로그인 실패'), ('CREATE_USER', '사용자 추가'), ('UPDATE_USER', '사용자 수정'), ('DELETE_USER', '사용자 삭제'), ('RESET_PASSWORD', '비밀번호 초기화'), ('UPDATE_ROLE', '권한 변경'), ('UPDATE_STATUS', '계정 상태 변경'), ('SIGNUP', '회원가입')], max_length=100, verbose_name='수행한 작업')),
                ('target_id', models.BigIntegerField(blank=True, null=True, verbose_name='대상 리소스 ID')),
                ('details', models.TextField(blank=True, verbose_name='상세 정보')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='작업 발생 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='이벤트 발생 시각')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='작업 수행자 ID')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그 목록',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
