# Generated by Django 5.2.5 on 2025-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', '로그인 성공'), ('LOGIN_FAILED', '로그인 실패'), ('CREATE_USER', '사용자 추가'), ('UPDATE_USER', '사용자 수정'), ('DELETE_USER', '사용자 삭제'), ('RESET_PASSWORD', '비밀번호 초기화'), ('UPDATE_ROLE', '권한 변경'), ('UPDATE_STATUS', '계정 상태 변경'), ('SIGNUP', '회원가입'), ('CREATE_PERFORMANCE', '실적 등록'), ('UPDATE_PERFORMANCE', '실적 수정'), ('DELETE_PERFORMANCE', '실적 삭제'), ('CREATE_NONCONFORMANCE', '부적합 등록'), ('UPDATE_NONCONFORMANCE', '부적합 수정'), ('DELETE_NONCONFORMANCE', '부적합 삭제'), ('CREATE_SCHEDULE', '일정 등록'), ('UPDATE_SCHEDULE', '일정 수정'), ('DELETE_SCHEDULE', '일정 삭제')], max_length=100, verbose_name='수행한 작업'),
        ),
    ]
