# Generated by Django 5.2.5 on 2025-10-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0007_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "로그인 성공"),
                    ("LOGIN_FAILED", "로그인 실패"),
                    ("SIGNUP", "회원가입"),
                    ("CHANGE_PASSWORD", "비밀번호 변경"),
                    ("CREATE_USER", "사용자 추가"),
                    ("UPDATE_USER", "사용자 수정"),
                    ("DELETE_USER", "사용자 삭제"),
                    ("RESTORE_USER", "사용자 복구"),
                    ("RESET_PASSWORD", "비밀번호 초기화"),
                    ("UPDATE_ROLE", "권한 변경"),
                    ("UPDATE_STATUS", "계정 상태 변경"),
                    ("CREATE_PERFORMANCE", "실적 등록"),
                    ("UPDATE_PERFORMANCE", "실적 수정"),
                    ("DELETE_PERFORMANCE", "실적 삭제"),
                    ("BULK_CREATE_PERFORMANCE", "실적 일괄 등록"),
                    ("BULK_CREATE_PERFORMANCE_CSV", "실적 CSV 일괄 등록"),
                    ("BULK_DELETE_PERFORMANCE", "실적 일괄 삭제"),
                    ("EXPORT_PERFORMANCE", "실적 내보내기"),
                    ("CREATE_NONCONFORMANCE", "부적합 등록"),
                    ("UPDATE_NONCONFORMANCE", "부적합 수정"),
                    ("DELETE_NONCONFORMANCE", "부적합 삭제"),
                    ("CREATE_DEFECT_TYPE", "불량유형 등록"),
                    ("DELETE_DEFECT_TYPE", "불량유형 삭제"),
                    ("CREATE_DEFECT_CAUSE", "불량원인 등록"),
                    ("DELETE_DEFECT_CAUSE", "불량원인 삭제"),
                    ("REORDER_DEFECT_TYPES", "불량유형 순서 변경"),
                    ("REORDER_DEFECT_CAUSES", "불량원인 순서 변경"),
                    ("EXPORT_NONCONFORMANCE", "부적합 내보내기"),
                    ("CREATE_SCHEDULE", "일정 등록"),
                    ("UPDATE_SCHEDULE", "일정 수정"),
                    ("DELETE_SCHEDULE", "일정 삭제"),
                    ("CREATE_CUSTOMER_COMPLAINT", "고객불만 등록"),
                    ("UPDATE_CUSTOMER_COMPLAINT", "고객불만 수정"),
                    ("DELETE_CUSTOMER_COMPLAINT", "고객불만 삭제"),
                    ("EXPORT_CUSTOMER_COMPLAINT", "고객불만 내보내기"),
                    ("CREATE_KPI_TARGET", "KPI 목표 등록"),
                    ("UPDATE_KPI_TARGET", "KPI 목표 수정"),
                    ("DELETE_KPI_TARGET", "KPI 목표 삭제"),
                    ("DOWNLOAD_BACKUP", "백업 다운로드"),
                    ("UPLOAD_BACKUP", "백업 업로드"),
                    ("AUTO_BACKUP", "자동 백업 생성"),
                    ("DELETE_OLD_DATA", "오래된 데이터 삭제"),
                ],
                max_length=100,
                verbose_name="수행한 작업",
            ),
        ),
    ]
